symbols.xml
=> Add start_dwarf_count for 0.40.24

df.viewscreen.xml
not sure whether the last field is part of the class or not
=> field names in viewscreen_topicmeeting_fill_land_holder_positionsst

symbols.xml
http://www.bay12forums.com/smf/index.php?topic=139553.msg5994915;topicseen#msg5994915
=> Add startdwarf address for windows

df.units.xml
Accordingly it seems that unk_3c could be renamed attack_accuracy?
=> Roses found the attack_accuracy field.

df.globals.xml, df.military.xml
~~There is still some questions. Would really love if somebody found the army_next_id offset.~~
=> some research (mostly guesswork) about armies.

df.world-site.xml
These values were reverse engineered using IDA and checked against a structure exported map in Legends mode.
The values are consistent with the values listed in the DF generated file structure_color_key.txt that details the RGB colors for each entry in the structure maps.
=> Changed df:world_site_realization::T_Areas.unk_0 to field named type

df.refs.xml
Discovered while reverse engineering with IDA the trading map exported in Legends Mode
=> Identify some fields in entity_site_link

symbols.xml
cross-checked against sv-esk's commit and confirmed same in all cases
=> 42.03: Linux: find-offsets results including ui_lever_target_type

df.viewscreen.xml
Identify some fields in df::viewscreen_export_graphical_mapst
=> Identify fields in viewscreen_export_graphical_mapst

df.world-site.xml
=> Added missing value in T_Areas::T_type enum

df.world-site.xml
changed the unknowns to name compound
=> name for underworld spire

symbols.xml
win32 start_dwarf_count symbol from AbdulovHell's DF Tool 2.3
Other found using evan's debugger
=> Add all remaining symbols

df.refs.xml
Found them using IDA and checked using gm-editor
=> Identify some fields in df::entity_site_link

df.item-raws.xml
weapon_attack.flags.flag-bit1 is [ATTACK_FLAG_INDEPENDENT_MULTIATTACK]
=> identify weapon_attack.flags.flag-bit1 

df.entities.xml
=> identiy vectors in df::historical_entity.T_diplomacy

df.world-site.xml
=> identify pointer type in df::world_site_realization

symbols.xml
As found by the find-offsets script.
=> 0.43.02 Linux symbols

symbols.xml
For inclusion in v43.02. I'll update them for each new DF releases
=> Added symbols and addresses for exportmaps plugin

df.buildings.xml
=> Identify fields in workshop_profile and simplify workshops/furnaces/traps

df.history.xml
abuse_type and props.pile_type converted to enums.
added a props compound for abuse_type hung.
=> history_event_body_abusedst

df.history.xml, df.knowledge.xml, df.refs.xml
Instead of having to go through a bunch of one-bit tests, this means the knowledge type can be used as an enum with switch statements and all the extra compiler stuff that comes with that.
Requires DFHack/dfhack#934
=> knowledge category flag

df.reaction-raws.xml
Signed-off-by: Michael Casadevall <mcasadevall@ubuntu.com>
=> Add two unknown paramteres to the produce vtable on reactions-raw

df.building-raws.xml
I only tested this on linux 64 bit.
=> building_def.build_key is long

Bitfield.pm
=> Remove non-trivial bitfield constructors

df.world.xml
=> Identify world.murky_pools

df.world.xml
=> Identify lists of skills per profession

df.advmode.xml
`SayNoOrderYet` is "You haven't ordered anything. Would you like something?".
`GiveSquadOrder` is a squad order. The only ones that seem to work are the orders to kill a historical figure and to drive a historical entity out of a site.
=> Identify two talk_choice_types

df.meeting.xml, df.refs.xml
This is my first pull request, please let me know if I got anything wrong.
=> XML changes for research-related data structures

df.history.xml, df.meeting.xml
I identified the structures where it keeps track of whether each historical figure knows each topic, and how close a scholar is to a research breakthrough.
=> More research related structures

df.viewscreen.xml
=> Some viewscreen_setupdwarfgamest alignment fixes

df.world-data.xml
New attempt... As far as I can see it's only 9 lines differing now.
=> #204, #217, rem white space

symbols.xml
Needed by pull-req: https://github.com/DFHack/dfhack/pull/1181
=> Add rendermap function address to 64bit oses

df.building-vectors.xml
Feel free to propose a better name for what was UNK_V42_1
=> missing buildings_other_id values

df.history.xml
Put histfig_id, birth_year and birth_second at the right offset.
=> Fix identity members order

df.world-data.xml
Closes #237 
Compiled without errors and verified the generated .h file contains the changes.
=> Identified dead_percentage and reanimating

df.history.xml
No related issue. Instead, this request is based on a forum DFHack thread discussion.
DFHack has been compiled without errors and the affected generated .h verified to contain the changes.
=> Identified relation fields

df.history.xml
named profession and civ fields for identity structure
=> identity fields

df.world-data.xml
=> Added feature map info comment

df.units.xml
Addresses the memory flag part of issue 255, but not the additional value one (which is in a different file)
=> Added memory flag to emotions

df.units.xml
As discussed in the forum thread: http://www.bay12forums.com/smf/index.php?topic=164123.msg7787172#msg7787172
=> Fix unit_personality current_focus and undistracted_focus

df.world.xml
Resolves issue #260 
#261 happened while I was doing this, and it took two attempts to sync that, hence 3 commits rather than 1.
=> Performance

df.world.xml
I couldn't find where the new pointers were used in DF
=> Add new world pointers (v0.44.11)

df.announcements.xml
Source:
data/init/announcements.txt
diff -ru df_linux_44.10/data/ df_linux_44.11/data/ | less
=> Add new announcement types

df.creature-raws.xml, df.entity-raws.xml, df.world.xml
This depends on https://github.com/DFHack/df-structures/pull/275 and https://github.com/DFHack/dfhack/pull/1326
=> Fix profession array sizes to include MESSENGER

df.art.xml
=> Added MESSENGER enum value

df.history.xml
Source: IDA/reading the code. I haven't yet checked if I have any in my test game.
=> Add new history_event subclasses

SYNTAX.rst, StructType.pm, df.jobs.xml, df.map.xml, df.projectile.xml, lower-1.xslt
=> Linked list

symbols.xml
\sa https://github.com/jjyg/df_misc/pull/9
=> Support dlsym loading from libgraphics vtables

df.world-data.xml
Corresponding changelog.txt text:
```
- Introduced mountain_peak_flags in order to introduce is_volcano flag.
```
=> Named is_volcano flag

df.art.xml, df.itemimprovements.xml
poetic_form mostly done at the moment
=> WIP art-related structures

df.ui.xml
This has to be tested on Windows (and 32bit I guess) but it looks logical enough.
=> fixing main/squads in ui

df.ui.xml, df.viewscreen.xml
Said structure is also used inside viewscreen_savegame
=> Update ui.main, identify sub-structure for nemesis offloading

df.history.xml, df.military.xml, df.ui-menus.xml, df.viewscreen.xml, df.world-data.xml, df.world-site.xml, df.world.xml
WIP but can be merged at any point I guess
=> misc research

df.items.xml, df.units.xml
As described by thefriendlyhacker here: 
http://www.bay12forums.com/smf/index.php?topic=164123.msg7827109#msg7827109
=> Named flags related to gelding

df.history.xml, df.interaction.xml, df.units.xml, df.world-data.xml
As per the title, alongside some miscellaneous stuff. I don't yet know how to properly format structures beyond giving them names and leaving comments. As such, I've tried to make the comments as detailed as possible to aid whoever gets around to formally editing this. Please let me know if anything's unclear.
=> Named various fields mostly related to undead

df.units.xml
=> Identified caste_flags in unit.enemy

df.art.xml, df.itemimprovements.xml, df.legends.xml, df.viewscreen.xml
=> Musical forms, plus some others from XML export

df.world.xml
and changed similar field in glowing_barrier from int8_t to bool
=> identified "triggered" in deep_vein_hollow

symbols.xml
ref https://github.com/DFHack/dfhack/pull/1476
=> add unit_get_physical_description symbol

df.advmode.xml, df.buildings.xml, df.creature-raws.xml, df.descriptors.xml, df.entities.xml, df.entity-raws.xml, df.globals.xml, df.history.xml, df.item-raws.xml, df.items.xml, df.language.xml, df.raws.xml, df.refs.xml, df.skills.xml, df.ui-menus.xml, df.ui.xml, df.units.xml, df.viewscreen.xml, df.world.xml
Updating various globals, one commit at time.
=> Updating structures for v0.47.01

df.announcements.xml, df.art.xml, df.d_init.xml, df.entities.xml, df.history.xml, df.map.xml, df.military.xml, df.refs.xml, df.units.xml, df.world-data.xml, df.world-site.xml, df.world.xml
I'd happily accept suggestions for better names for the first and second stages of temple/guild petitions.
=> identified temple/guild fields

df.units.xml
Addresses the first point of issue #346 (I'm not addressing the issue with hash here, as that seems to cause auto resolution, and this is only one part of it).
=> Aligned performance_skills

df.refs.xml
Verified using the religion maps from legends mode, this bit flag seems to indicate a town or place is the holy city of a religion.
=> Add holy city entity_site_link flag

df.units.xml
Reported here: https://github.com/Dwarf-Therapist/Dwarf-Therapist/issues/197
=> fix unit personality focus fields

df.legends.xml, df.refs.xml, df.world-data.xml, df.world.xml
Rather significant amount of "research notes", but given the amount of guess work I think it might be useful to know where it came from, as well as some kind of guide to possibly get some info out of the fields.
=> entity site link research/identification

df.art.xml, df.military.xml, df.world-data.xml, df.world.xml
Partial army_controller research
=> partical army_controller research

df.buildings.xml
Also requires DFHack-side changes in the buildings module
=> Convert building_extents_type to an enum

df.items.xml
=> Some dye values discovered.

df.history.xml, df.itemimprovements.xml, df.world.xml
=> Identified various divination-related fields

.gitignore, .pre-commit-config.yaml, df.announcements.xml, df.creature-raws.xml, df.d_init.xml, df.meeting.xml, df.refs.xml, df.viewscreen.xml, df.world-data.xml, how-to-update.rst, list.pl, lower-2.xslt, start-utils.lisp
See https://github.com/DFHack/dfhack/issues/2075
=> pre-commit config

changelog.txt, df.announcements.xml
=> "sparring" bit is inverted, rename "hostile_combat"

changelog.txt, df.vermin.xml
Identified in version 0.28.181.40d, confirmed still accurate in 0.47.05
=> Identify `vermin.unk_34` as "category"

df.map.xml
=> Add comments for adventure use of designations

changelog.txt, df.ui-menus.xml, df.ui.xml, df.units.xml
* ui_build_selector - min/max weights, current walk tag
* ui - infiltrator reference vectors
* unit - misc_trait_type comments, mostly auto-decrement markers
=> Assorted updates

changelog.txt, df.history.xml
Whenever any visitor arrives at the fort, these two fields log the year and ticks of their arrival
=> Label two fields in reputation

changelog.txt, df.units.xml
=> Unit action type groups

changelog.txt, df.items.xml, df.projectile.xml, df.refs.xml, df.world.xml
this is the various updates to structures from me for november 2022
=> structure updates for november 2022

df.graphics.xml, df.skills.xml, df.ui-menus.xml, df.units.xml, df.world-site.xml
Apparently, Toady changed something between .02 and .03
=> Realign graphicst, identify vectors at start

df.entities.xml, df.graphics.xml, df.items.xml, df.refs.xml, df.skills.xml, df.ui-menus.xml, df.ui.xml, df.units.xml, df.viewscreen.xml
* Correct graphicst (missing vector in texture data)
* Add renderer_2d[_base]
* Identify shared structure between viewscreen and game
* Fix world_gen_param vmethods and subclasses
* Fix profession enum
* Fix Classic minimap dimensions
* Add missing fields to Statue and Corpse items (latter unused?)
* Add vector index caches to some objects
* Realign plotinfo.unk_v50_1, fix layout
* Identify new entity_activity_statistics fields
=> Various fixes

df.world.xml
Been given permission to talk about headers and structures and things, so I'm just going to add stuff as I need it (turns out Lua scripting is real helpful for debugging without needing to recompile, whoop)
=> Unit handler: added unit_context_block, renamed 'bad'

df.itemimprovements.xml
The string is initialized to the instrument_piece.type string
=> unk_2 in itemimprovement_instrument_piecest is type

df.units.xml
and add anonymous member visible in unitst::read_file
=> unitst: move `riding_item_id` below `corpse_parts`

df.item-raws.xml
=> realign all itemdefs

StructFields.pm, df.viewscreen.xml, lower-1.xslt
Cherry-pick of https://github.com/DFHack/df-structures/pull/500
Requires https://github.com/DFHack/dfhack/pull/2547
=> [v50] Add stub std::map support to codegen

df.jobs.xml, df.legends.xml, df.stockpile.xml, df.ui.xml, symbols.xml
=> rename latent "ui" fields to "plotinfo"

data-definition.xsd
=> add stl map to the dtd

changelog.txt, df.buildings.xml
=> Named the variables used for archery range direction

df.unit-thoughts.xml
Co-Authored-By: Clément Vuchener <clement.vuchener@gmail.com>
=> add new unit_thought_types

df.ui-menus.xml, df.world.xml
Hopefully this should actually be semi-correct now.
=> Realign world, Toady-ify

df.buildings.xml
I spent a while figuring out some of the fields, this is what I've got so far! I've got a rough idea of what dir_x and dir_y are like but I need to figure out how to work the codegen to express it all correctly
=> Civzone structure update

df.military.xml
This is also based on quietusts fork, which realigns squad
=> Identify some new squad fields, squad alignment

df.units.xml
Left some stuff blank because I don't know if it's used or not. Putting this here since it all seems like good stuff for utilities, especially the new stress bit and the slacking numbers.
=> Filling out some personality info

df.items.xml
Tests if item satisfies material flag based on its item_type, item_subtype, mat_type, and mat_index. IDK if there's a better name for it than `testMaterialFlag`.
=> vmethod_81 tests material flags

df.items.xml
Code looks like this:
```
bool vmethod_137(df::item *item)
{
if (item->item_flags.bits.removed)
return false;
else if (!item->item_flags.bits.in_inventory)
return true;
for (size_t i = 0; i < item->general_refs.size(); i++)
{
auto ref_type = item->general_refs[i].getType();
if (ref_type == general_ref_type::CONTAINED_IN_ITEM)
{
auto outer_item = item->general_refs[i].getItem();
if (outer_item)
return outer_item.vmethod_137();
}
else if (ref_type == general_ref_type::UNIT_HOLDER)
return false;
}
for (size_t i = 0; i < item->specific_refs.size(); i++) // useless loop
{
if (item->specific_refs[i].type == specific_ref_type::VERMIN_ESCAPED_PET)
return true;
}
return true;
}
```
=> Name item vmethod_137

df.world-site.xml
This doesn't really affect much as there's a function to fetch this, but I thought I'd file this before I forgot
=> abstract_building_hospitalst contains an abstract building contents (thanks quietust!)

changelog.txt, df.units.xml
affects `occupation` and `adjective`
=> correct misalignment in unit

changelog.txt, df.refs.xml
deets mostly provided by putnam
=> realign and augment `entity_site_link`

df.units.xml
the result of a bit of digging from earlier today
=> some visitor info

df.military.xml
A few were short, and a few others were missing
This should resolve the latest problem found in #538
=> Update army_controller substructs

df.descriptors.xml, df.entities.xml, df.viewscreen.xml
Also realign the new_region viewscreen, had an int32 which should've been int16.
=> Realign descriptors and agreement details

changelog.txt, df.art.xml
Hospitals are now a location, and have a corresponding occupation
=> add new occupation types

df.items.xml
Method is called at end of `assignQuality`. Update return types to `item_quality`.
=> Item vmethod_107 is assignQuality2

df.ui.xml
Confirmed through disassembly equivalent of resetDwarfmodeView
=> plotinfo->main._unk_v50_2 is mode

df.d_init.xml, df.keybindings.xml, df.ui-menus.xml, df.world.xml
* gamest
* d_init
* world
Also add new interface_key names.
=> Realign for 0.50.07

df.ui-menus.xml
Needed by buildingplan for placing buildilngs.
It would be nice to know the correct names, though.
=> name some buildreq fields

df.art.xml, df.history.xml, df.units.xml
* historical_figure_info.masterpieces
* historical_figure_relationships.intrigues.unk12
* unit_emotion_memory
Also get rid of the "beat" structure, since it doesn't appear to be necessary.
=> More struct realignment

changelog.txt, df.entities.xml, df.history.xml, df.world.xml
* fixed alignment in `world.status`
* minor (probably inconsequential) type updates for a few history events
=> misc 5007 updates

changelog.txt, df.globals.xml, df.ui-menus.xml, symbols.xml
this splits gamest into two chunks to allow us to support both steam and classic editions of DF
=> split gamest

changelog.txt, df.meeting.xml
turns out it was changed at the same time as dipscript_popup
=> fix activity_info

symbols.xml
I guess this address is generated by some script but I don't where it is.
I cannot check itch address, I don't if it is correct.
=> fix game_extra address for 50.07-classic

df.ui-menus.xml
Based on disassembly of v50.05's `sub_14096E700` and called functions.
=> Identify some info about markup_text_boxst unk1

changelog.txt, df.ui.xml
Based on observation using `gui/gm-editor`.
=> Name plot_infost unk_8 and some of its fields

changelog.txt, df.history.xml
presumably deleted along with everything else related to architects
=> remove `history_event_masterpiece_created_arch_designst`

changelog.txt, df.interaction.xml, df.jobs.xml, df.pathfinding.xml, df.ui-menus.xml, df.world.xml
wrapup of various things i've been working on
=> assorted structure updates

df.units.xml
this is one that came to me from putnam and one that i did a while ago but somehow misplaced
=> 5007 updates

changelog.txt, df.entities.xml, df.world.xml
1: divine_treasure
2: encased_horror
Also identify fields in deep_vein_hollow, glowing_barrier, cursed_tomb
=> Identify mapevent_v50_1+2

df.jobs.xml
=> add gems to dfhack_material_categories

changelog.txt, df.ui-menus.xml
=> fix name of mod_headerst flag

changelog.txt, df.ui-menus.xml, df.world.xml
=> identify unit creation fields in arena

symbols.xml
this should be done "permanently" in our generator, though
=> rename to what the vtable search expects

df.graphics.xml
the `std::variant` representation may not be the best
=> update graphics with sdl2 changes

changelog.txt, df.world-site.xml
identified for `quickfort` location creation
=> identify abstract_building_contents fields/flags

changelog.txt, df.skills.xml
``Cheese Maker`` --> ``Cheesemaker``
``Bee Keeper`` --> ``Beekeeper``
``Bone Setter`` --> ``Bone Doctor``
=> Update profession caption names for v50

changelog.txt, df.world-site.xml
otherwise the library doesn't work
=> initialize library vars as the game does

changelog.txt, df.units.xml
we figured these out back in february but somehow it never made it into structures
=> realign misc_trait_type enum

.github/workflows/build.yml, .github/workflows/check-type-sizes.yml, .github/workflows/comment-pr.yml
removes docs step (I couldn't find anything that it was testing for this repo) and adds test step
=> use reusable test action from the dfhack repo

changelog.txt, df.viewscreen.xml
This adds some missing fields to the end to make the structure the correct size. There may be additional adjustments still needed.
=> update to `viewscreen_legendsst`

.github/workflows/build.yml, .github/workflows/check-type-sizes.yml
=> align with the new repository-agnostic workflows

Common.pm, StructFields.pm, data-definition.xsd, df.globals.xml
Not possible to test in-game yet, pending more work on https://github.com/DFHack/dfhack/issues/3668
=> Add original-name attributes to globals

df.globals.xml
According to the global table and a string dump
=> Remove globals removed in v50

.github/workflows/check-type-sizes.yml
ref: https://github.com/DFHack/dfhack/issues/3680
=> adjust to pre-archived artifacts

changelog.txt, df.ui-menus.xml, df.ui.xml
Thanks, Rumrusher!
https://github.com/DFHack/dfhack/issues/3606
=> name tutorial-related fields

df.meeting.xml, df.ui.xml
* Update dipscript_info, remove filename
* Add dipscript_text, for what used to be in data/dipscript/text
* Remove plotinfo.parties (long gone), add "dipscript_texts" nearby
=> Dipscript updates

df.advmode.xml
based mainly on version tracking 50.09->50.10
=> realign `adventurest`

changelog.txt, df.globals.xml, symbols.xml
=> start dwarf count

df.entities.xml, df.jobs.xml, df.ui-menus.xml, df.ui.xml, df.units.xml, df.world.xml
this PR reflects a number of updates derived from structure information provided by bay12
=> miscellaneous updates from bay12 provided info

changelog.txt, df.legends.xml, df.viewscreen.xml
required for searching the world artifacts list
=> define fields used by viewscreen_worldst

changelog.txt, df.globals.xml
=> add `buildingst_completebuild` global

changelog.txt, df.ui.xml
and add observed initial values
=> [burrow] add graphics mode texture and color fields

changelog.txt, df.jobs.xml
in service of https://github.com/DFHack/scripts/pull/799
=> identify additional job_item_flag3 flags

df.advmode.xml, df.buildings.xml, df.creature-raws.xml, df.descriptors.xml, df.entities.xml, df.history.xml, df.itemimprovements.xml, df.legends.xml, df.map.xml, df.meeting.xml, df.pathfinding.xml, df.raws.xml, df.refs.xml, df.ui.xml, df.units.xml, df.viewscreen.xml, df.world-site.xml, df.world.xml
this is a large collection of structure updates based on study of the headers provided by bay12
none of these should require any changes to dfhack code; many of them are just comment updates
=> collected structures update

StructFields.pm, data-definition.xsd, lower-1.xslt
expected to be needed in the future
=> add `std::weak_ptr` support to codegen

changelog.txt, df.art.xml, df.ui-menus.xml, df.world-site.xml
and use it where it was referenced in existing structures as a comment
=> Define occupationst and related structures

df.viewscreen.xml
not in sources, based on observation
=> realign site finder enum values

df.globals.xml, df.history.xml, df.military.xml, df.viewscreen.xml, df.world.xml
in an attempt to understand those parts of the data structures a little better
=> name a bunch of military- and savegame-related fields

df.entities.xml, df.history.xml
corrects one typo, identifies two `unk`s, and adds a bunch of comments
=> updates from bay12 on some history related stuff

df.globals.xml
required in order to make the method call callable from dfhack
=> add bay12 unitst::choptree method call

.github/workflows/build.yml
match the branch name in the dfhack repo for the test build
=> if we're building or merging to an alternate branch

changelog.txt
to test new branch coordination logic in CI
=> merge master into 5012-beta

.github/workflows/build.yml
as per Discord discussion: https://discord.com/channels/793331351645323264/857489615299411968/1201709761515761735
=> for other forks, always build against develop

.github/workflows/check-type-sizes.yml
not just ones against the master branch
=> make the size check build action work for all PRs

.github/workflows/build.yml
pairs well with https://github.com/DFHack/df-structures/pull/718
=> fail header generation step if codegen.pl returns non-zero

df.art.xml, df.world-site.xml, symbols.xml
A few errors I found. I don't know the reason for the duplicate vtable-address, a script may need fixing.
=> Small fixes

changelog.txt, df.skills.xml
as per comments in https://github.com/DFHack/dfhack/pull/4282
=> correct moodable property for several professions

changelog.txt, df.building-vectors.xml
depends on synchronized changes to preserve-tombs.cpp
=> add more specific types for building_other vectors

df.legends.xml
needed for https://github.com/DFHack/scripts/pull/1005
=> name some unknown invasion info fields

df.entities.xml, df.meeting.xml, df.ui-menus.xml, df.units.xml
several element types were thoroughly scrambled here
=> correct `main_interface.diplomacy`

changelog.txt, df.ui.xml
though existing named fields are not renamed
=> canonicalize plotinfo.hauling

changelog.txt, df.plants.xml
needed to fix issues with autochop's log estimation routine
=> define tree flags

df.creature-raws.xml, df.entities.xml, df.interaction.xml, df.jobs.xml, df.raws.xml, df.world-data.xml, df.world-site.xml
and assorted other canonicalizations
=> add several worldgen-related types

changelog.txt, df.job-types.xml
for use by `blueprint` when interpreting active dig jobs
=> create Carving job class

changelog.txt, df.plants.xml
Info from Quietust on Discord.
=> Comments for plant flags

changelog.txt, df.jobs.xml, df.map.xml, df.ui-menus.xml
will need usage to be adjusted in the plugins and Job module
=> define job.specflags union

changelog.txt, df.items.xml
@quietust noted on [discord](https://discord.com/channels/793331351645323264/807444047215853578/1241212934936330290) that the last two items were out of order. corrected, and comments added based on bay12 information.
=> correct `slab_engraving_type`

df.map.xml, df.world.xml
=> canonicalize `world::map_extras`

df.world-data.xml
Fill in more of df.world-data.xml
=> More world_data fields and substructures

df.announcements.xml, df.creature-raws.xml, df.d_init.xml, df.descriptors.xml, df.entities.xml, df.entity-raws.xml, df.history.xml, df.language.xml, df.military.xml, df.raws.xml, df.world.xml
A bunch more in this batch:
* creatures + creature-raws
* entities + entity-raws
* d_init (this will require some plugin/script changes)
* descriptors, language
* a few minor tweaks to other files (because of cross-referenced types)
=> Sync more structures

df.entities.xml, df.history.xml, df.items.xml, df.jobs.xml, df.knowledge.xml, df.syndrome.xml, df.unit-thoughts.xml, df.units.xml, df.world.xml
(and a handful of related bits in other files)
=> Sync history structures to Toady headers

df.advmode.xml
PR for testing the windows build with union structures
=> test barebones union

df.job-types.xml, df.jobs.xml, df.legends.xml, df.machines.xml, df.map.xml, df.pathfinding.xml, df.projectile.xml, df.reaction-raws.xml, df.resource.xml, df.skills.xml, df.tile-types.xml, df.unit-thoughts.xml, df.vermin.xml, df.world-site.xml
Mostly minor stuff, hopefully not too many breaking changes this time.
=> Sync assorted structures to Toady headers

df.job-types.xml, df.map.xml, df.ui.xml
also fix generation of flow_type enum
ref: https://github.com/DFHack/df-structures/pull/774
=> fix references to old field names

df.advmode.xml, df.art.xml, df.entities.xml, df.items.xml, df.jobs.xml, df.knowledge.xml, df.meeting.xml, df.military.xml, df.ui-menus.xml, df.ui.xml, df.units.xml, df.world-site.xml
=> Sync meeting/military/plotinfo structures to Toady headers

df.entities.xml, df.history.xml, df.interaction.xml, df.itemimprovements.xml, df.map.xml, df.ui-menus.xml, df.vermin.xml, df.viewscreen.xml, df.world-data.xml, df.world-site.xml, df.world.xml
=> Sync site/region/world structures to Toady headers

df.world-site.xml
Fix a few mistakes from my last update
=> Fix world_site_realization

df.creature-raws.xml, df.graphics.xml, df.items.xml, df.meeting.xml, df.refs.xml, df.ui-menus.xml, df.units.xml, df.world-site.xml
Turns out I missed a few during canonicalization - this should hopefully be all of them
=> Identify remaining "unk" fields

df.creature-raws.xml, df.entities.xml
Found while reviewing 0.31.25 structures (since I had copied them over under the expectation that most of them would match - as it turns out, they did)
=> Assorted fixes

df.meeting.xml
Not sure why I missed these - I can only assume I got distracted.
=> Add missing flag names

df.advmode.xml
Add new adventure movement classes, remove old entries from ui_advmode_menu (and add labels to all of the others so it'll be easier to handle such changes later)
=> Remaining fixes for 51.01-beta21

df.advmode.xml, df.graphics.xml, df.map.xml, df.ui-menus.xml, df.viewscreen.xml
Also attempted to realign graphicst - please verify that the structure size matches what's in the globals table!
=> 51.01-beta24

df.ui-menus.xml
updates hover instructions to canonical names
based on 04e2b18 by @quietust
this will allow dfhack/scripts#1333 to be merged to 50.14 develop
=> canonicalize hover instructions

.gitattributes
ref: https://github.com/DFHack/scripts/pull/381
=> set merge strategy to union for changelog

df.globals.xml
=> revert incorrect change to gametype and gamemode

df.ui.xml
df headers has the components of this field as `corner_x`, `corner_y`, and `corner_z`
=> canonicalize name of field

df.g_src.init.xml
Evidently, I got distracted near the end and only made this change half-way
=> Fix init_display

df.building.xml, df.d_init.xml, df.g_src.init.xml, df.itemdef.xml
changes required for compatibility with DF 51.11
note that this _will_ break the `Buildings` module and the `preserve-rooms` plugin
=> 51.11 compatibility

df.building.xml
new fields were added in the wrong place and broke alignment
=> Fix stockpile_parameter_finishedst
