df.projectile.xml, df.units.xml
Toady confirmed that projectile flags 12 lets units land on their feet, hence safe_landing. Putnam found that the unit.actions.data.attack.unk_30 field is the actual velocity, hence attack_velocity. So here they are.
=> safe_landing and attack_velocity seem apt

df.item-raws.xml, df.job-types.xml
MakeInstrument is no longer a supported job type, and there are new tags allowed in raws for tools.
Depends on dfhack/dfhack#770 for plugin compilation.
=> Instrument research

df.art.xml, df.viewscreen.xml, df.world-site.xml
also removes two incorrect field names. there is no setting for wanted bookcases and the field that was previously identified as type is 2 for a tavern and a temple I have but 0 for a library.
=> identify two fields in occupation

df.refs.xml
This was the answer from Toady about this field values  from a question asked by me in the last Future of the Fortress thread in DF Forums.
They are used extensively in diplomacy, trading and nobility map exports
=> Identify field as flags and its values in df::entity_site_link

df.units.xml
contains string for new 42.06 feature "Used adjectives from physical
descriptions for use in adv mode creature designations"
updates #79
=> add new unit stl-string

df.world.xml
required for https://github.com/DFHack/dfhack/pull/838
> 08:47 < angavrilov> lethosor: the constructor problem can be solved by injecting a friend declaration - viewscreen is an example
> 08:48 < angavrilov> using the custom-methods system
> 08:49 < angavrilov> constructors are protected to force the use of df::allocate, but such cases of nested structures are a special case that needs a hack
=> use custom-methods for building_handler and machine_handler

df.syndrome.xml, df.units.xml
unk_v4201_1a - vector contains needs
unk_0 need-type - seems to be already known (df.units.xml contains enum for it)
unk_4 deity historical figure - only for pray need. -1 for all others needs
unk_8 focus_level - less means more distracted(more time passed since last satisfyed)
unk_c need_level - how fast distraction_level value decreases when it below 0
unk_v4201_1 - bitfield
second byte is up when unit is unfocused or distracted on at least one need
unk_v4201_2 - pointer to trait array. Values are signed int16, same order in unit_personality.traits (personality_facet_type enum has base type uint16_t -works fine in lisp tool but not in gm-editor). Values represents temporary deltas(changes) in traits applied by syndromes(inebriation or so). You can see "he is currently more rude" and so …
=> identify some unit_personality fields 

df.history.xml, df.itemimprovements.xml, df.units.xml
unit_soul.unk_v42_1  points to a structure that contains four vectors with information about unit's skill in musical instruments(concrete instruments, not general instrument type), poetic forms, musical forms and dance forms
Values in these structures are simply instrument/poetic/music/dance form id, skill level and experience on current level. No rust/unused or so counters.
historical_figure_info.secret.read_books - vector contains read by unit books (their ids), including most choreoghaphy, musical compositions and poems that it can perform. Few remaining things that unit (at least adventurer) can perform are prefomance_forms themselves. Stories are also not here.
2 new written_content_types - musical composition and choreography
=> identify some perfomance-related fields

df.military.xml, df.resource.xml, df.world-site.xml
Checking DF code with ÍDA in Windows shows that the constructor for df::world_site_realization allocates more memory than the size showed in the symbols.xml.
This new space is used for a array of 20 pointers and a totalizer similar to the previous ones and a std::vector of pointers.
Unfortunately, I think that the pointer points to a local subtype created inside df::world_site_realization  with a size of 420 bytes, so I defined the pointer as void* until I can identify this type.
Also site_realization_building_type has 22 types, not 20 as before. Types 21 and 22 are marked unknown_1 and unknown_2 respectively.
These new enums are used in the new arrays mentioned above.
Finally, the names building_type_5 and building_type_13 are changed to well and temple, as those are its names according …
=> Added missing fields and rename a fews others in df::world_site_realization

df.interaction.xml
Added names for interaction_id and region_index in interaction_instance. Tested in 42.06.
I tried changing the interaction_id to change which interaction was applied to the region indicated by the region_index. (formerly anon_1 and anon_3) The weather in the evil region changed as expected. 
I haven't tried any more exotic changes (interactions in non-evil regions, multiple interactions per region), but the structure appears to describe one interaction per evil region, so it works for reporting on all evil weather.
=> Added names in interaction_instance.

df.world.xml
This field is recalculated on world load, instead of saved.
Required by the stockflow and df-ai plugins.
=> Identifying the next_id field for manager orders.

StructFields.pm, StructType.pm, df.graphics.xml, df.knowledge.xml, df.map.xml, df.materials.xml, lower-1.xslt
For wrappers to be generated, they have to be included in a `<custom-methods>`
node, similar to the existing `<virtual-methods>`:
```xml
<custom-methods>
<cmethod name='foo'/>
</custom-methods>
```
The actual method signatures and definitions are still kept in custom/*.methods.inc
=> Make wrappers for custom methods in lua possible

df.itemimprovements.xml, df.items.xml
Finally got around to doing this myself: this names the item_flags2 flag and the vector in itemimprovement_writingst which are used for written contents things in quires, scrolls, and books.  
The name for the flag comes from the [HAS_WRITTEN_CONTENTS] requirement in the BIND_BOOK reaction.  The name for itemimprovement_writingst::anon_1 comes from the apparently-identical vector in itemimprovement_pagesst.  (I haven't personally seen a pagesst, myself, but the ref says it points to written_contents, and that's what the writingst one does.)
=> Identify written contents variable and flag names

df.advmode.xml
I’m not sure these proposed names are clear, but they’re better than `unk4`. The two vectors are vectors of indexes into `choices`; can that be expressed with `refers-to`? Something like `$$._parent.choices[$]`?
=> Identify some conversation fields

symbols.xml
Update for win32 symbols based on my analysis.  Removed keydisplay since it crashes my df and I'm not familiar with the address.   
I am not familiar with testing and analysis tools used by the team so these have only been evaluated static code inspection between the 0.43.03 and 0.43.05 images.  
I offer the update in case it speeds up someone else's analysis.
=> Update win32 global symbols

df.history.xml
Just as `killed_site` is a list of site IDs where unimportant things were killed, `killed_underground_region` and `killed_region` are lists of underground region and region IDs.
The `skeletal` bit in `killed_undead` was a relic of old versions of the game where creatures could be skeletons or zombies. Zombies live on in the current night creature ark but skeletons are no more.
=> Name two historical_kills fields and remove the skeletal flag

df.advmode.xml
The `A_TRAVEL_HIDE_INSTRUCTIONS` key (default: h) cycles through the last four enum values. `TwoBlankRows` (or any unnamed value) reserves two rows below the map like `TwoRows` but leaves them blank. It does not occur in the vanilla game.
=> Expand show_menu from a bool to an enum

df.entities.xml
entity.resources.organic.anon_1 should be changed to entity.resources.organic.parchment
I found that anon_1 holds parchment material entries while researching how to modify parchment materials in a civilization for https://github.com/rndmvar/DFHack_scripts/blob/master/populate.rb
=> Identified entity.resources.organic.anon_1

df.units.xml
Discovered that skill.unk_1c equals NATURAL_SKILL in the creature's caste raws.  This was found while doing research into FPS loss due to excessive skill rust calculations in game. (Pro tip: Don't train 100+ dwarves in skills, and then let them social/idle for long periods of time.)
=> Found that skill.unk_1c is NATURAL_SKILL level

df.entities.xml
Value 62 in DFHack::EntitySellCategory should be Parchment.  I've got working code at  the following link that allows for adding and removing creatures and their materials from the trade agreement, as well as the civilizations resources lists.  Currently it only runs on the latest DFHack version, as it requires the Ruby 2.0.0 interpreter shipped with it.
https://github.com/rndmvar/DFHack_scripts/blob/master/populate.rb
=> Add Parchment to DFHack::EntitySellCategory

df.military.xml
There are two corresponding classes, `squad_order_kill_hfst` and `squad_order_drive_armies_from_sitest`, but I don’t know how to investigate new classes.
=> Identify two squad_order_types

df.entities.xml, df.entity-raws.xml, df.world-site.xml
Resolves #50.
There should probably be a test that the count of every static array is at least the number of values of its index enum, if it has one. For example, with the addition of `KNOWLEDGE` there are now 33 `value_type`s, so it no longer makes sense for a 32-element array to be indexed by `value_type`.
=> Investigate cultural values and ethics

df.entities.xml
`SPECIAL_BURIAL` and `REQUIRES_MARKET` correspond to the raw tags with the same names. I don’t know what `unk_1f` is but it is true for some positions.
=> Identify two entity_position_flags and name an unknown one

df.viewscreen.xml
`decade` is the year of the historical map in legends mode divided by 10. Exceptionally, a `decade` of 0 is displayed as the year 1.
=> Identify the decade for historical maps

df.history.xml
The new enum is related to `unit_relationship_type`. The enum values given names are those for which strings appear in legends mode. 20 and 21 are attested and are probably `Poet` and `Bard` but I couldn’t verify that.
=> Identify some reputation fields

df.world-site.xml
`group_log` lists every change to the list of entities associated with the cultural identity.
`unk_24` and `unk_34` go together but I couldn’t figure out what they do. They look like {4,5,6} / {2000,6000,2000}. There always three elements, except for some which are {3} / {10000}. `unk_24` can also be {0,1,2}. The elements of `unk_34` always sum to 10000. I assume they are proportions.
Some mountain halls’ cultural identities have an `unk_f4` of 800000. All other cultural identities have 0.
=> Identify the change log of a culture's membership

df.plant-raws.xml
`index` is the index of the `plant_raw` in the instance vector, as reported in #195. I could have added `key-field='index'` to the struct definition but chose not to, because `df.plant_raw.find` already works, so changing it to use binary search is unnecessary.
`stockpile_growths` is a vector of indices into `growths` corresponding to growths that are marked with `[STOCKPILE_PLANT_GROWTH]` and also `[EDIBLE_RAW]` or `[EDIBLE_COOKED]`. Inedible growths do not go in food stockpiles, so the former tag alone does not qualify a growth for this vector.
`stockpile_growth_flags` is a vector of bitfields associated with the growths identified by `stockpile_growths`. Each bitfield reports whether the growth is edible raw or cooked. Inedible growths are not listed in this vector so the bitfield is …
=> Identify some plant_raw fields

df.history.xml, df.meeting.xml, df.world-site.xml
These commits identify the purpose of two previously-unknown parts of the location information. The first is a list of scribing jobs to be performed at the location; the commit identifies almost all of the fields involved. This is important for fixing library bugs. The second turns out to be a list of visitor reports/reputation -- several of the fields seem to have larger values for "better" locations, but I haven't identified the specifics yet. They may identify things like the number of musical performances, poetic performances, etc. the person witnessed, the value of the location, the presence of alcoholic drinks, etc. (Note that these reports appear several in-game weeks after the visitor has originally departed your site -- presumably when the historical figure finishes their journey …
=> Location structures for scribe jobs and visitor reputation

df.world-site.xml
This one is annoying me when I try to use the structures xml. If I read the documentation correctly, this is a typo.
=> fix bitfield-type used as a nested bitfield

df.history.xml
I screwed up when when naming the fields, causing the fields to be one field off. The original anon_2 is still unidentified and should end up as anon_2 again, while the original anon_5 should be "rank", not anon_2.
=> Corrected named fields: Were one field off

df.items.xml
I noticed that anon_1 was mapping to a bitfield. It became quickly
clear that the bitfield is corpse_flags. After checking that unit_id2 is
actually used I decided to swap anon_1 and corpse_flags offsets.
=> Fix offset of item_body_component->corpse_flags

df.creature-raws.xml
There is a new profession but I don't know name for it (yet).
13 unknown ints with padding after 7th in 64bit system. 32bit
system has all 13 ints without padding.
It is possible that there is more new entries after profession_name because I only quickly glanced for obvious offset issue but I didn't notice any.
=> df::creature_raw offset fix

Enum.pm
Seeing enum values in header makes it easier to match those values to
dissambler numbers. This helps me with both gdb and IDA. IDA has descent
suppot for offsets and constands but it requires manual setup. To help
matching values manually I like to browser headers in my source editor
because it is the fastest tool to find types and variables.
=> Add hex values to df enums

df.ui-menus.xml
DFHack's `core.cpp` will need to be updated to refer to `df::global::ui_sidebar_menus->command_line.original` instead of `df::global::ui_sidebar_menus->command_line.raw`.
=> sync ui_sidebar_menus.command_line with g_src

df.ui.xml
I mapped both structures in ida using. unk_44_12f isn't visible in initial xrefs. Finding it an verifying its sizes would take a bit longer. But padding before it strongly suggest that there must be 4byte value in 32bit and 64bit systems (unless there is a structure border)
=> Add 0.44.12 unknown member variables to ui.squads

df.units.xml
Determined by just modifying attacks as they happen. Disabling flags[14] made a spar report into a combat report, disabling flags[11] made a sparring attack into one that did real damage. unk_38 was 103 for punches and df.job_skill[103] is GRASP_STRIKE.
=> Filled out some attack knowledge.

df.art.xml, df.entities.xml, df.history.xml, df.military.xml, df.world.xml
Note the renaming of `read_books` to `known_written_contents`. This is more accurate as `read_books` implies the artifact or item ID of books read, which is not the case, as this is a list of written_content IDs. More importantly, the ID of art form derivations including choreography and musical compositions known to the historical figure are also listed here, as these derivations are stored in the form of a `written_content` despite being unrelated to books. `read_books` does not currently seem to be used by any scripts in the repository.
=> Named fields related to art and belief systems

df.world-data.xml
No actual logic changes.
Instead, the changes are additional comments regarding how DF generates 'incursions', i.e. biomes jutting into mid level tiles from adjacent tiles.
In addition to this, some comments have been moved from XML only comments to comment attributes and tags to appear in generated XML files.
Finally, some basic range info has been added for region map entry attributes involved with biomes.
Note: due to a weirdness in the .h file generation process comments on compounds end up twice in the .h file. However, I consider it better that it appears twice than not at all.
This pull request closes the information part of issue #323, but the part regarding gui/gm-editor remains open.
=> Commented incursion logic plus minor items

Bitfield.pm, Common.pm, Enum.pm, StructFields.pm, StructType.pm, codegen.pl, df.graphics.xml
Support header dependecies
This allows removing Core.h include from DataDefs.h.
Include all dependecies in df headers
Include all dependecies in df headers  …
This allows including df/*.h without including any dependecies first. It
also helps ycm error reporting to avoid wrong errors when opening
headers when it tries to compile header as c++ source file.
=> Add header dependencies

df.viewscreen.xml
The names come one-to-one directly from the associated strings, like for example "Loading units..." becomes LOADING_UNITS.
=> viewscreen_loadgamest::cur_step

df.units.xml
Add emotion_memory field: optional array used to store past emotions that can be later copied back
in the emotions vector with a "remembered" flag.
Most fields are copied from and to emotions, so they are easy to identify. Except for the unnamed one, it could be flags or unk7, or something completely different, it is only initialized to 0 in what I have seen.
The count for the static-array is uncertain, it is based on a single code path, but the size is hard-coded (both in the call to new and the constructor), so it would be surprising to be a variable length array.
Only based on linux64 for now. I may do a bit more research before I call it done, but comments are welcome.
=> Emotions research

df.items.xml
some experimentation with the 2nd argument to `item::getItemDescription` shows that it affects the plurality of the returned string.
=> add comment to getItemDescription's 2nd parameter

df.entities.xml
This identifies the unk23 and unk24 in entity resources as the fore and background colors for their entity symbol used in the historical maps and entity list in legends mode.
I hope I set the type name correctly? I am still a bit shakey on how the struct definitions work exactly
=> identify the entity colors

df.world-site.xml
This specifies the lair types as discussed in #336.
I ended up calling the last entry 'Wilderness Location' as that is what the wiki uses for the Roc Nests, and I didn't want to have a split in terms.
https://dwarffortresswiki.org/index.php/DF2014:Lair
=> Specify lair types

df.creature-raws.xml, df.entity-raws.xml
For the creature_raw_flags I ran a script that matched presence/absence of flags against the tags present in the raw structure, on top of/confirming previous research in issue #102.
I found it useful to reference the controlling tags directly as comments, and so added them.
For entity_raw I noted that the first named field matched the index of the element (as is normal for raws), and that the second named field looked like the raw tag structure present in other raw entries, and verified that I did indeed get the tags out of it when first reinterpret_cast (Lua) and then typed (XML and code generation).
=> Identified creature flags, associated to tags. Named entity_raw fields. Issue #102

df.legends.xml, df.world-data.xml
Not sure what has happened, but all that padding that aligned the values at the end before doesn't work. This commit matches with the same elements of the same (copied) save in 0.44.12, and the forces vector contains the same element as they did before (field called unk_1f0 in the old DFHack version used with 0.44.12).
I haven't found any values but 0 in the saves I checked for the unk_v47_1 and unk_v47_2 fields.
=> Corrected world_region to align min/max/mid values at the end

df.viewscreen.xml
Fixes DFHack/dfhack#1494.
Please check that the removal of the field was a mistake before accepting this PR.
Restoring the field allowed the script to export the maps, and the ones I looked at were different from each others, though.
=> restored sel_idx field that went AWOL

df.world.xml
This records and sets the tame/mountable status when the arena mode creature creation menu is opened.
0 = not tame/mountable
1 = tame/mountable
Perhaps it should be a bool?
=> arena_spawn: named 'tame'

df.interaction.xml
Ascertained by examining which of the two was set for a modded interaction with the relevant token in gui/gm-editor.
=> interaction_effect_location_hint: arranged order

df.history.xml
- Removed some fields at the end of history events to try to get them to be the right size.  Looked at the results of `df::history_event::write_file()` to try to verify the correct number of fields.
- Removed some int32 fields that appeared before std::vector fields.  These fields ended up being padding in 64-bit builds and broke the vectors in 32-bit builds.
- Renamed a bunch of fields roughly based on the contents of Legends XML export
- Figured out the names of some other fields by trial and error, i.e. substituting in values to see how they changed the event sentences.
- Removed the `since='v0.47.01'` attribute on just the `history_event_type` enum values to make that file a little more readable.
- Added fields for the `SABOTAGE` event based on feedback from quietust
=> Second pass on history events

df.history.xml, df.military.xml, df.unit-thoughts.xml
Based on vector/pointer checking on linux32. But some fixes affect both bitness like `army.controller_id` or the unknown fields in `identity` (previous fields were containing uninitialized data). Tested on linux32/linux64 only.
=> Various fixes

df.history.xml, df.meeting.xml, df.ui.xml, df.world.xml
I think the incident subtype value 1 corresponds to Crime. In one of the saves I used the "Crime" incidents matched up with convictions as well as crime entries on the Justice screen. In the other no Injustice system had been used, so there were no convictions, but quite a few "Crime" incidents. Enabling the Injustice system showed a lot of incidents, but it wasn't possible to match them up with the incidents, as there appeared to be no witnesses, and thus no indication of whether the incident report "killer" was actually the criminal, while it matched up in the save with the convictions.
The evidence is a bit thin for the naming of the field, but it's gone unidentified for quite a long time, and I think it's better with an uncertain identification than none at all.
A new 0.47.X vector …
=> Identified incident crime, reordered features

df.creature-raws.xml
I've renamed a bunch of creature and caste flags to use their official names as indicated by Toady in the latest Future of the Fortress edition (March 2020): http://www.bay12forums.com/smf//index.php?topic=169696.msg8099138#msg8099138.
I verified the position of the new flags (and many of the previously identified ones) by checking the flag index set in the interaction effect of modded summoning interactions making reference to them (see DFHack/df-structures/pull/375).
This will of course require changes to any scripts/plugins using the old flag names.
=> Use the official creature and caste flag names

df.interaction.xml
Determined by observing modded interactions using gui/gm-editor.
I believe that a `required_creature_flags` field should also be present (probably above `forbidden_creature_flags`), as it is possible to specify these in the interaction raws, but it seems to be missing from the mapped structures at present.
=> Named some summoning effect fields

df.history.xml
As indicated in DFHack/scripts/pull/103.
`modtools/create-unit.lua` appears to be the only script which makes reference to `unit_id2`, so this change shouldn't involve much work.
=> historical_figure: renamed 'unit_id2' to 'nemesis_id'

changelog.txt, df.entities.xml, df.history.xml
This PR requires some extra reviewing and coordination, as it affects Units.cpp and remotefortressreader.cpp as well (a PR will be produced for that after this one).
Toady has thrown us a curve ball in the form of a varying type field. df.identity's field identifying who the character assuming the identity really is is usually a histfig reference, but for some reason it's a nemesis_record reference when it's a spy/criminal.
The good news is that I think I've identified the enum field used to determine the type of identity, while the bad news is that 2½ out of 6 values are unknown, as I haven't seen any examples of them in the two worlds examined. The ½ value is 0, which I haven't seen, but the Units.cpp code implies is used for cursed creatures to hide their identities.
The cases seen are …
=> identity identification, affects Units.cpp

df.world-site.xml
This extends the site realiziation type enum with the new buildings, and identifies some entries in the abstract buildings as indicated in #397
I would like to visit a vault still to double check if that's the last site realization building entry missing, and my world has a vault in the middle of elf-sites, so maybe I could figure out if I can find a bit more for the elf sites too. That's gonna take a bit though.
=> Name several building related items.

df.ui.xml
As described by Toady [here](http://www.bay12forums.com/smf/index.php?topic=169696.msg8195533#msg8195533): 
_"When you go to choose a specific item, there are several lists sitting around from back in the arsenal dwarf days - that's an array of item ptr vectors with size item_type_number (ie, a vector of weapons, a vector of helms, etc.).  That's sitting up in the global fort information structure (legacily called 'plotinfo' but I dunno what you all call it -- it has your civ id and the number of reserved bins, tons of fort-type info, along with these item array-vectors which live in a member structure that has equipment data), and there are three arrays like this, one for **'unmanifested' items**, one for 'unassigned' items, and one for 'assigned' items."_
`plotinfo` almost certainly …
=> ui.equipment: rename items_by_type1 -> items_unmanifested

df.creature-raws.xml
Tied to the [SYNDROME_DILUTION_FACTOR](https://dwarffortresswiki.org/index.php/DF2014:Creature_token#SYNDROME_DILUTION_FACTOR) creature token.
=> Identified 'syndrome_dilution_identifier' and 'syndrome_dilution_factor'

df.world-data.xml
- for consistency: landmasses, regions, rivers have their own separate type
- tested for non-regression with exportlegends and a c++ plugin
=> Create separate type-name for 'mountain_peak'

changelog.txt, df.art.xml, df.language.xml, df.unit-thoughts.xml
The changes affect the strangemood plugin as it has a "case" statement listing some of these values.
Edit: The added "empty" beat enum value was added because I've seen it used in a save, but as that pattern wasn't actually used in any music exported legends info doesn't provide any description of it.
=> identified a few enum values

changelog.txt, df.art.xml
Realized you can do the same trick as with unit thoughts, i.e. hack the unknown values in and then see what DF generates (in this case in the form of exported Legends XML).
That didn't work out for the dance moves, though, as DF didn't generate anything identifiable...
=> identified remaining beat enum values

df.advmode.xml
Regarding `track_viewed_unk_1` and `track_viewed_unk_2` - currently userdata; there should probably be a
`track_viewed_z` field somewhere in here to complement `track_viewed_x` and `track_viewed_y`.
Similarly, `player_unit_projectile_unk` should probably contain `player_unit_projectile_x` and `player_unit_projectile_y`.
=> More ui_advmode naming

df.history.xml
Moddable gods doesn't work without referring to this variable, which is an anon variable for now, which is sure to result in bad news later. Not sure if `spheres.spheres` is okay, but it's better than anon_1.
=> Give the spheres vector a usable name

df.jobs.xml
Decoration jobs use this union to specify the item improvement type.
Directly lifted from @quietust's suggestion on Discord:
https://discord.com/channels/793331351645323264/807444467140788254/890981752598843462
=> Add improvement type to job union

changelog.txt, df.history.xml
This is the abstract account used for gambling, trading, buying properties, embezzling, sabotage etc, as determined via checking.
``df.historical_figure.T_skills``: name `account` field
=> Name hist fig account

.github/workflows/build.yml
Repeat of #455, since PRs cannot be reopened if their branches are force-pushed while they were closed.
----
This should help catch issues like the changelog entry introduced in #451 sooner.
Dropped "Check for missing docs" (script-docs.py) step because scripts aren't added in df-structures.
=> GitHub actions build docs

df.announcements.xml
``duration`` and ``display_timer`` values are in graphical frames. Each report line ticks down from 100 before the next line is displayed in the announcement bar. When the last report line is displayed, ``display_timer`` ticks down from the value it was set to. If no new report occurs to reset it, the announcement bar will clear when it hits -1. Some actions like entering a full screen menu will clear all timers.
``display_timer`` value of 2000 is more typical of DF announcements. Value of 5000 is used for "taken by strange mood", but is a bit long to be suited as our default. At 30 GFPS, that's 1.1 minutes versus 2.8.
=> Announcement display timers are tied to GFPS

df.advmode.xml, df.art.xml, df.buildings.xml, df.creature-raws.xml, df.entities.xml, df.graphics.xml, df.history.xml, df.interaction.xml, df.itemimprovements.xml, df.items.xml, df.jobs.xml, df.language.xml, df.legends.xml, df.map.xml, df.meeting.xml, df.military.xml, df.raws.xml, df.reaction-raws.xml, df.refs.xml, df.resource.xml, df.syndrome.xml, df.ui-menus.xml, df.ui.xml, df.units.xml, df.viewscreen.xml, df.world-data.xml, df.world-site.xml, df.world.xml
DFHack/dfhack#2219
Because otherwise people will use them in scripts, which is bad because removing/renaming one anon field renames ALL OTHER anon fields in the same structure.
Next step: update codegen to forbid unnamed fields so this never has to be done ever again.
=> De-anon-ify all structures.

changelog.txt, df.items.xml
itemst vmethod 106 is called to notify of the creation of a masterwork. there are three arguments. the first is definitely a pointer to a unit; the other two are unknown at this time
=> update itemst vmethod 106

codegen.pl
As discussed on the DFHack Discord, this should fix some issues in regards to building DFHack when the path to it has spaces, as `glob` interprets the spaces as separating different patterns to glob. One could fix this by simply wrapping the string in more quotes, but I believe a more robust approach would be to use `bsd_glob` instead, which does not use spaces as separators (and the intent of the code, as far as I can tell, is to only glob with one pattern anyway).
=> Fixed the globbing in codegen.pl to support paths with spaces.

df.globals.xml, df.graphics.xml, df.init.xml, df.viewscreen.xml
* Fix enabler.textures and enabler.sync
* Update texture_handler+tile_page, rename to restore "st" suffix, and move into df.graphics.xml
* Sync init and sub-structures
* Identify new viewscreen vmethods
* Removed layer_object and KeybindingScreen, neither of which exist anymore
NOTE: some of these changes will require additional DFHack updates
=> Update more globals from g_src

StructFields.pm, df.viewscreen.xml, lower-1.xslt
Fixes #498
Requires https://github.com/DFHack/dfhack/pull/2532
Deliberately targeting v0.47.05 first since this was tested there (and fixes an alignment issue)
=> Add stub std::map support to codegen

df.advmode.xml, df.globals.xml, df.ui-menus.xml, df.ui.xml, symbols.xml
`ui_advmode` -> `adventure`
`ui` -> `plotinfo`
`ui_sidebar_menus` -> `game`
`ui_build_selector` -> `buildreq`
also associated types
per discussion on discord
a collateral change will need to be made to `dump_df_globals.rb` in df_misc: https://github.com/DFHack/df_misc/pull/25
=> rename a handful of globals to match toady names

df.viewscreen.xml
still have not found how this bleeds out of `viewscreen_adopt_regionst` into somewhere it can be accessed outside of load/save
=> identify where timeline is stored in savefiles

df.buildings.xml
I wasn't quite sure what the protocol was here for a uint64_t union, so I opted to stick the raw flags in a struct
This breaks remotefortressreader as it relies on dir_x and dir_y, and I'm not quite sure what the protocol is here for syncing changes with the main repo with this change. The fix is this https://github.com/20k/dfhack-ui/commit/90a4ea8d938ca22184210aca2945338fc8693d0e
I've tested setting all these flags manually, and it all seems to work and sync up with the UI
=> Zone settings flags

changelog.txt, df.entities.xml, df.ui.xml
Fixes DFHack/dfhack#2636
Fixes DFHack/dfhack#2631
also update plotinfo to correct position of civilian alert id
Co-Authored-By: Quietust <1005195+quietust@users.noreply.github.com>
=> realign historical_entity

df.military.xml, df.ui.xml
I discovered that the length of anon_1 exactly matches the new squad routines. civ_alert_idx appears to be dead, and instead is a next id counter for the routines
The void* isn't a T_schedule* or a df::squad_schedule_entry*, which is where my reverse engineering abilities end. Figuring it out would be necessary for the ability to programmatically make squads
I renamed the military squad variable as it now definitely is not an alert, but a routine instead. It does however still point into the same element, but I thought it might be worth changing this in case people are using it to look into the alerts struct
(refiled the PR because the commits came out weird)
=> Identify contents of routines vector

df.creature-raws.xml, df.military.xml, df.plant-raws.xml
=> realign: `creature_raw`, `army_controller`, `plant_growth`

changelog.txt, df.entity-raws.xml, df.history.xml, df.language.xml, df.world.xml
* add "HOSPITAL" name type
* remove "Buddy" and "Grudge" reputation types (which were deprecated in 47.05 and actually deleted in v50)
* add "Hospital" language name category
* note the "this day in history" table (formerly `unk_v40_6`) that SeerSkye found, with appropriate adjustments
Co-Authored-By: SeerSkye <58483868+SeerSkye@users.noreply.github.com>
=> various updates

df.keybindings.xml
Now we can type again in the various gui windows.
I also checked that D_PAUSE is properly passed through to the game, so I think these new enums lay somewhere in this general area.
=> Fix key offsets

.github/workflows/check-type-sizes.yml
Formerly, the submodule ref from dfhack/dfhack:develop was used as the base, which produced spurious reports of changed sizes if df-structures:master was newer.
=> check-type-sizes workflow: Use base branch of PR for comparison

df.ui-menus.xml, df.world.xml
Also identify the first field as a "splitmix64" state. No idea what the other fields are for.
=> Identify new RNG state var in world

df.military.xml, df.ui.xml
This sets the initial values for various unks that were largely found via memory inspection, though the changes to squad_order were found very kindly by ab9rf via reverse engineering
The change to equipment update in ammo was discussed a while back in the discord (search for 2047 for info), but never formally committed. These changes are collectively for the military module PR
=> Init values for military, extract equipment update

changelog.txt, df.ui.xml
Fix crashing when accessing these vectors in `gui/gm-editor` or lua.
=> Convert plotinfo.equipment vectors from pointers to refs

changelog.txt, df.refs.xml
These ref types were removed in v50, causing misalignment of the remaining values.
Closes #549
=> Remove specific_ref_type BUILDING_PARTY, PETINFO_PET, and PETINFO_OWNER

df.history.xml
If `units.active[0]` has a relationship with a target whose current identity has an entry in the respective `hf_visual`'s `unk_2v` vector, then the target's visible name appears after their title (e.g., "the deity" or "Slave") regardless of the `information_source` flag not being set or not sharing the same `cultural_identity`.
=> hf_visual unk_2v is identity ref

changelog.txt, df.ui.xml
These fields are (probably) needed to implement quicksave, see https://github.com/DFHack/scripts/pull/639
=> identified fields needed for quicksave

changelog.txt, df.stockpile.xml
Toady added a separate "corpses" vector which we had inadvertently stuffed into `refuse`; this breaks it out to its own subsection and realigns the rest of `refuse`
=> realign `stockpiles_settings`

df.ui.xml
I am not sure about the bitfield size, but I cannot check right now.
I have no idea where the stuff I'm removing has gone, but it's not the first time in this structure from the comments. There are two bytes of padding after `chores`, bools could fit in there.
=> Identify chores related fields in plotinfo.hauling

changelog.txt, df.plants.xml
I discovered this from dumping the tree body data to make a visual bitmap of the tree structure. When we interpret each element as 8 bits, there were gaps between adjacent trunk tiles and the trunk is not centered in the tree dimensions. With a 16-bit tree body data element, trunks are adjacent and centered, and match the visual representation of the in-game trees.
Why did the bit size increase? Are there more flags now in the enum? I'm not equipped to divine that knowledge.
The impact of this change is that `Designations::markPlant()` will now mark the correct (southeast) tile of 3x3 trees instead of the (unreachable) center tile. Also, autochop will get the right count of trunk tiles for estimating log yield, which should fix its chronic under-estimation issues.
=> fix size of tree body data

StructFields.pm, StructType.pm, codegen.pl
This is needed because class-type constructors (i.e. constructors for types with vmethods) are protected.
For instance, in the SDL2 beta builds, there is a `widget_textbox` (which has vmethods) contained in `MacroScreenSave`. This prevented the default `MacroScreenSave` constructor from compiling. Adding a friend declaration allows `MacroScreenSave` to invoke the constructor for `widget_textbox`.
We actually have a few cases of this already (`interfacest` contains a `viewscreenst`, `world` contains a `machine_handlerst`), and we have previously worked around this issue by adding `custom-methods=true` to the affected classes, then adding friend declarations to the `df/custom/*.inc` files in the dfhack repo. This change makes that unnecessary, but I am opting to hold off on cleaning up …
=> codegen: generate friend declarations for classes that contain members with vtables

changelog.txt, df.tile-types.xml
based on research by @plule 
necessary to implement suspendmanager @plule also found evidence that other tools are working around this being wrong
see dfhack/dfhack#3492
=> change `tiletype_shape::RAMP_TOP` `walkable` attr to false

df.ui-menus.xml
also gave the anons "real" names sorta
not important enough to changelog tbh
=> some structure partially identified in assign_trade

df.units.xml
pool_index in particular I'm using for debugging some, so it's good to keep it around; cached_glowtile_type is used for a line-of-sight optimization and should generally be irrelevant, but might be usable for some "aggressive, incorrect" optimizations done at runtime, by setting it to 0--anything set to 1 will check the raws in line-of-sight code for every unit within 26 tiles and anything set to 2 will check if it has an eye popped out, while 0 will just assume there's no glowtile at all and run with that--faster, but technically incorrect, one of those things that can be tweaked at runtime now.
Should be noted that pool_index is `protected`, which means how it's aligned might end up being compiler-specific--the standard only specifies that all variables of the same access specifier are …
=> Some more unit info for 50.09

df.meeting.xml, df.units.xml
this structure was recently discovered in diverse investigations. it appears to have been added to df somewhere between 40d and 34.05, possibly as early as 31.01, but we only recently became aware of it
per comments from putnam, it is involved in line-of-sight processing. it is also associated with unit movement and job handling, and is associated with 50.09's multithreaded performance improvements
the reason we're including it in structures is this structure is the type of one of the arguments of one of `activity_eventst`'s vmethods
=> `process_unit_aux`

changelog.txt, df.military.xml, df.ui-menus.xml
* squad_orderst: add "isEqual" vmethod, fix return type on "process"
* build_req_choicest: realign, fix vmethods
=> A few updates

df.graphics.xml
Should double-check that the size of gps remains the same (221160) on Windows.
=> Fix gps alignment on Linux

changelog.txt, df.viewscreen.xml
most of the structure has been recovered from the destructor, but a few fields have been identified by reverse-engineering `viewscreen_new_arenast::logic`
=> add `viewscreen_new_arenast`

df.buildings.xml
wasn't an issue on Windows, but causes misalignment on Linux
=> [buildingst] remove field that isn't actually there

df.viewscreen.xml
These seem to line up in memory (strings have reasonable contents), so I believe the types are correct.
A couple unresolved questions from my end:
* `loadgame_save_info.anon_1` (the `void*` before `folder_name`) doesn't look like it's actually a valid pointer on my end
* `loadgame_save_info` starting at `folder_name` has an identical structure to `world_dat_summary::T_unk` starting at `unk_3`. Is it possible these are the same structure? I'm not sure if their various strings are being used for the same purposes. Some contain folder names, some don't.
=> viewscreen_titlest: identify a few fields based on sizes

df.items.xml, df.pathfinding.xml, df.units.xml
* identify an unknown field in `item_eggst`
* add a bitfield for pathfinding flags, based mainly on @quietust's 40d research; this is mostly used only internally but it is exposed to structures in `unitst`
* (added) remove two fields from `work_detail` which are apparently padding per comments from putnam
=> misc updates

changelog.txt, df.items.xml
identified a significant number of anonymous vmethods in `itemst`
also cleaned up the index numbers in the xml, they were badly out of whack
=> itemst vmethod update & housecleaning

df.viewscreen.xml, df.world.xml
the regrouping of these fields as a subcompound is because they are being passed around as a unit in the actual code
this has no consumer-facing impact; this is far too deep in the weeds
added: realign `widgets::button` and `widgets::textbox`
=> various 50.09 realignments

StructFields.pm, data-definition.xsd, lower-1.xslt
support for std::function is currently halfassed, we only handle the return type for now but at least will let us get alignment correct
=> add codegen support for `std::function` and `std::optional`

df.world-data.xml
Based on info from Bay12
Would appreciate if someone could verify this on Windows before merging
=> Realign world_data around constructions

df.advmode.xml, df.entities.xml, df.history.xml, df.itemimprovements.xml, df.items.xml, df.jobs.xml, df.refs.xml, df.unit-thoughts.xml, df.units.xml, df.world-site.xml
this PR updates several structures definitions with information from the headers provided to us by bay12
some infrequently used types have been renamed (most notably `job_cancel`, which is a research-only type at this point), while more frequently used types have had their bay12 names logged (as `original-name` when our DTD allows it, as a comment when it does not) without changing their names in dfhack. a couple of enums had `NONE` (-1) values that we did not previously have in our definitions
none of these changes should have any implications for existing code
=> selective update from bay12 info

df.announcements.xml, df.world.xml
this change requires a coordinated change in dfhack due to this type being in use
=> rename `report_init` to `announcementst` and identify unknown fields

df.history.xml, df.units.xml, df.world.xml
`witness_report` -> `witness_incidentst`
`crime_witness` -> `witness_reportst`
our names for these types were similar to bay12's name in a way that was going to be perpetually confusing
also unified and corrected the `witness_type` enum (bay12: `Witness`) which was incorrect in both places it appeared separately
=> update & rename some intrigue/crime related types

df.skills.xml
Based on skill displayed in the work detail screen.
`HUNT` labor is associated with multiple skills. I did not find any usage that would break from that kind of change (I did not find any usage for this attribute actually except [mine](https://github.com/cvuchener/df-workdetailtest/blob/911c94ebfb482cf6c670945676f8cd166978e295/src/WorkDetailColumn.cpp#L103-L105)).
=> Update job_skill's labor attribute

df.units.xml
This change is based on analysis of bay12-provided information and correctly reflects the actual type in the structure
This change requires a coordinated change to DFHack - see DFHack/DFHack#4068
=> change `unitst::owned_buildings` to `vector<building_civzonest*>`

StructFields.pm, data-definition.xsd, lower-1.xslt
this is a fairly brutal hack to allow `std::variant` to appear in structures
the attribute `raw-type` is used to specify the C++ type string that will appear between the brackets when instantiating the type. no processing of this type is done by codegen. note that `<` and `>` are special in XML and will have to be substituted by `&lt;` and `&gt;`
note also that this does not deal with identity trait issues at all; an `OPAQUE_IDENTITY_TRAIT` will be needed to be added to `DataIdentity.h` and `DataIdentity.cpp` for each specialization of `std::variant` that results from the use of this specification
=> brutal hack to support `std::variant`

df.globals.xml
Fix `game_mode` and `game_type` enums by removing `num` value and setting `NONE` to `-1`.
=> Fix game_mode and game_type enums

df.announcements.xml
From current available [g_src/basics.h](https://github.com/Putnam3145/Dwarf-Fortress--libgraphics--/blob/172e9946f95019edf6083cefe3328eb1d6d4079b/g_src/basics.h#L489):
Update `announcement_type` enum with `UNUSED` and `num` entries.
Create `announcement_alert_type` enum for future use.
=> Update announcement enums from g_src/basics.h

df.world.xml
Looks like the mutex `unk_v5010_1166a8` is in `world.status` based on its use here (v50.11 win64 Steam, `make_announcement` function):
```
14005765b LEA       RSI,[RDI + 0x43c0]
140057662 MOV       qword ptr [RBP + -0x30],RSI
140057666 MOV       RCX,RSI
140057669 CALL      qword ptr [->MSVCP140.DLL::_Mtx_lock]
```
where `RDI` is `world.status`.
I renamed the mutex `announcement_mutex`, since `world.status` is `announcement_handlerst`. Not sure if the mutex has a purpose beyond that.
=> Move mutex into world.status

df.announcements.xml
Add an enum-attr to `announcement_type` enum to retrieve the relevant `announcement_alert_type` enum associated with it. The relevant switch is found in `FUN_14005e5f0(report *)` for v50.11 win64 Steam.
=> Add enum-attr alert_type to announcement_type

df.announcements.xml, df.units.xml, df.world.xml
Identify `announcement_alert` fields based on use in `make_announcement` (`FUN_1400574e0` v50.11 win64 Steam.) Naming the struct `announcement_alertst` based on convention.
Additionally defined the `alert_button_announcement_id` vector as `int32_t`, since it uses `report.id`.
=> Identify world.status.announcement_alert fields

changelog.txt, df.announcements.xml, df.raws.xml, df.ui.xml
`world.raws.unk_v50_2` seems to be raws for music tracks, based on some conditions tested in a function (0x14030df60 win64 Steam) that references it. One of those conditions tested (at 0x14030f92e) was `(plotinfo.unk23c8_flags >> 7) & 1`, which is `caverns_opened` via process of elimination (confirmed ingame.)
`world.raws.unk_v50_3` seems to be raws for sounds, based on use in `make_announcement` function (0x1400574e0 win64 Steam.)
=> Identify music and sound raws; plotinfo.unk23c8_flags.caverns_opened

df.raws.xml
`class-type` is _only_ to be used for compounds that have a vtable
closes dfhack/dfhack#4229
=> `soundst`: `struct`, not `class`

df.unit-thoughts.xml, df.units.xml
warning: this breaks misery.cpp, add-thought.lua, and export-dt-ini.lua; coordination required
mappings for updating references in the foregoing:
* `unit_personality::T_emotions` -> `personality_moodst`
* `unit_personality::T_emotions::unk2` -> `personality_moodst::strength`
* `unit_personality::T_emotions::strength` -> `personality_moodst::relative_strength`
* `unit_personality::T_emotions::unk7` -> `personality_moodst::next_overcome_timer`
i don't believe any of the flags added by this PR were being used as `unk`s
=> canonicalize `unitst::emotions`

df.buildings.xml, df.entities.xml, df.history.xml, df.meeting.xml, df.refs.xml, df.stockpile.xml, df.ui-menus.xml, df.units.xml, df.world.xml
this PR contains an assortment of changes to structures to either use bay12 names for types and fields, or note what the bay12 names are
this PR seeks to avoid any changes that would conflict with existing code; changes that require coordination will be proposed separately
=> assorted canonicalizations

df.buildings.xml
in service of https://github.com/DFHack/dfhack/pull/4380
=> udpate building_drawbuffer

lower-2.xslt
This PR prevents dangling text nodes from making their way into `codegen.out.xml`. Some free-form comments would be duplicated and left dangling, making it slightly more difficult to parse "real" comments for the Lua annotations. Cheers.
Here is a git-diff of the XML output: [codegen.diff.txt](https://github.com/DFHack/df-structures/files/14815162/codegen.diff.txt)
=> Prevent codegen comments from being duplicated

changelog.txt, df.announcements.xml, df.units.xml
#714
Accidentally deleted repository before merge.
=> Announcement_infost flag indicates sparring; identify unit_action_data_attack flag

symbols.xml, symbols_gen_common.sh, symbols_gen_linux.sh, symbols_gen_windows.sh
automates Linux symbols.xml updates
=> automated symbol generation scripts for Linux and Windows

changelog.txt, df.map.xml
`caption` and `plant_raw_flag` attributes for `biome_type` enum. Will help simplify `gui/biomes.lua` and updates to `regrass` plugin.
=> Add biome_type attrs

codegen.pl
this causes codegen to exit with a nonzero error level if any of its internal eval blocks `die`
=> make codegen return a useful errorlevel

StructFields.pm
as per Discord discussion: https://discord.com/channels/793331351645323264/807444047215853578/1241770443371839488
This came up because the new df::job::job_spec union was not getting initialized on construction, even if `init-value` attributes were added to the fields.
This appears to be because the union is a mixture of plain data types (uint32_t) and bitfield types, which have non-default constructors. The end result is that no constructors get called and the resulting value is garbage.
This change zero-inits union structures. Existing code that *does* set the union fields will still work since the fields are set in the constructor for the containing class, which executes after the memset introduced here.
=> zero-init otherwise uninitialized unions

df.art.xml, df.building-raws.xml, df.building-vectors.xml, df.buildings.xml, df.stockpile.xml
And fix a few minor errors in the process
=> Sync Art and Buildings against Toady headers

StructFields.pm, df.advmode.xml
This prevents linkage errors on Windows where multiple anonymous structs or unions are declared in the same namespace. These symbols weren't useful to export anyway (AFAICT).
=> don't publicly export structs and unions that have no names

df.entities.xml, df.history.xml, df.interaction.xml, df.item-raws.xml, df.item-vectors.xml, df.itemimprovements.xml, df.items.xml, df.materials.xml, df.military.xml, df.plant-raws.xml, df.plants.xml, df.syndrome.xml, df.units.xml
Note that there are multiple breaking changes in this update:
* Item weight is now `massst`, which will also be used in `caravan_state` once I get to that
* `spatter` now includes `spatter_common` as a member rather than inheriting from it (so that we won't need padding hacks anymore for GCC)
* `itemst::testMaterialFlag` was wrong and has been changed to `itemst::fitsCivRequestTab`
* Any call sites for `itemst::addWear` or `itemst::checkWearDestroy` should be checked, as their parameters were out of order
* `itemst::getItemDescriptionPrefix` now uses an enum for its second parameter
* Anything looking at `item_history_info` previously expected a pointer-to-pointer; now there's an actual structure in between
* Anything still looking for the material flag `LEAF_MAT` will finally need to be …
=> Sync item/material structures to Toady headers

df.materials.xml
We really shouldn't be using "inherits-from" for copy/paste avoidance, because Windows and Linux have different rules for alignment/padding when subclasses are involved.
=> Undo changes to material_common

df.plants.xml
Enum attrs to restore convenience of `plant.flags`.
I assume it's not possible to have an enum attr that refers to a plant vector? Would be handy otherwise.
=> Enum attrs for plant_type

StructFields.pm, data-definition.xsd, lower-1.xslt
Companion to https://github.com/DFHack/dfhack/pull/4591
Not necessary to merge until we need it.
=> Support stl-array

df.buildings.xml, df.entities.xml, df.globals.xml, df.history.xml, df.jobs.xml, df.ui-menus.xml, df.ui.xml, df.viewscreen.xml, df.world-data.xml, df.world.xml
I think this might be the last of them!
=> Sync user interface structures to Toady headers

df.advmode.xml, df.interaction.xml, df.world.xml
I strongly suspect all of the enums in adventurest will result in conflicts due to their "NONE" values (like they did in `main_interface`) - if they do, I'll split them out .
=> Sync adventure structures to Toady headers

df.units.xml
`unit.appearance.colors[i]` refers to the unit's `caste_raw.color_modifiers[i].pattern_index`, based on Stonesense code.
That is, `caste_raw.color_modifiers[i].pattern_index[colors[i]]` will get you the index of the relevant `df.descriptor_pattern`.
=> unit.appearance.colors ref target

df.graphics.xml
because its very existence causes alignment errors on Windows.
Also fix the texture_indices lengths so they're hopefully correct.
=> Remove gps "texture" compound

df.graphics.xml
based on https://github.com/DFHack/df-structures/commit/3b029079b7efd2f664c9fb5567dca68b11755c19
=> attempt to realign with master changes

changelog.txt, df.world-site.xml
Switching to Bay12 names since they make more sense and we aren't using these anywhere.
Related to #443
=> Rename world_site.is_mountain_halls and world_site.is_fortress

df.units.xml
Add enum attrs so all `unit_action_type` enums are in the `All` `unit_action_type_group`.
They may also need attrs for `Movement`, `MovementFeet`, `Combat`, and/or `Work` (however we decide that).
=> Add "All" group attr to new unit_action_type enums

df.graphics.xml, df.jobs.xml, df.viewscreen.xml
This does not include viewscreen_adventure_logst because we don't actually have that screen right now.
Do not merge until we've compared the new size of `graphic[st]` to what's in the EXE's global table entry for `gps`.
=> update remaining structures for 51.01-beta20

SYNTAX.rst, changelog.txt
Here are a few spelling fixes.
If the non-Future changelog should be considered immutable I can re-roll without that change.
=> docs spelling fixes

df.viewscreen.xml
I'm not sure how these escaped canonicalization. I thought we had already done this on the 50.14 branch when it was `testing`
=> canonicalize widget flag names

changelog.txt, df.globals.xml
adds bay12 exported function so it can be called from dfhack code
=> add `unitst_set_automatic_professions`

df.advmode.xml, df.announcements.xml, df.creature-raws.xml, df.d_init.xml, df.entities.xml, df.entity-raws.xml, df.graphics.xml, df.history.xml, df.init.xml, df.interaction.xml, df.item-vectors.xml, df.items.xml, df.materials.xml, df.meeting.xml, df.raws.xml, df.syndrome.xml, df.ui-menus.xml, df.units.xml, df.viewscreen.xml, df.world-site.xml, df.world.xml
Hopefully I didn't make too many mistakes
=> 51.01-beta26

df.globals.xml
need to remember to check and update this with each release
=> expand global table size

df.graphics.xml
`graphicst` should now be size 0x37520 (226592) on Windows.
=> Further updates for 50.15

df.ui-menus.xml
so we can use it for focus string generation
This enum is represented by a bare int32_t in the DF headers, but has enum-like semantics in actual usage. I'm representing it as an enum for convenience and clarity.
=> add enum for work order condition change type

SYNTAX.rst, StructFields.pm, data-definition.xsd, lower-1.xslt
This adds codegen support for `stl-fs-path`, representing `std::filesystem::path`
This can be applied immediately as there is no change in behavior for structure definitions that do not actually use `stl-fs-path`
=> add codegen support for `stl-fs-path`

df.adventure.xml, df.creature.xml, df.d_basics.xml, df.d_interface.xml, df.g_src.keybindings.xml, df.item.xml, df.itemdef.xml, df.job.xml, df.proj.xml, df.unit.xml
Do not merge until 51.12 is actually released, since we might end up needing additional changes
=> Update structures for 51.12

df.d_init.xml, df.event.xml, df.history_figure.xml, df.rhythm.xml, df.scale.xml, df.unit.xml
This has no effect on DFHack - it just ensures that our Ghidra analysis scripts assign the correct class/type names
=> Add missing original-name attributes

df.block.xml
The only structural change was putting `blockst` into an object pool, which gives it a new `size_t pool_id;` field.
=> Update structures for 52.05
